apiVersion: v1
kind: Service
metadata:
  name: devops-demo-api-service
spec:
  type: LoadBalancer
  selector:
    app: devops-demo-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
